trigger:
- master
- develop
- feature/*

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build & Test'
  pool: $(defaultPool)
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js 12.x'

    - script: npm install
      displayName: 'Install dependencies'

    - script: npm run test:ci
      displayName: Run tests

    - task: PublishTestResults@2
      displayName: Publish test results
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'junit.xml'
        mergeTestResults: true
        testRunTitle: 'Unit tests'

    - task: PublishCodeCoverageResults@1
      displayName: Publish code coverage results
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: 'coverage/cobertura-coverage.xml'

    - script: npm run build
      displayName: 'Build application'

    - task: CopyFiles@2
      inputs:
        Contents: |
          build/*
          package.json
          package-lock.json
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
        preserveTimestamp: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathToPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'app'
        publishLocation: 'Container'
